config/routes.rb
Biblio::Application.routes.draw do
  devise_for :users

  resources :pages
  resources :books
  root to: "pages#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :isbn, :publisher, :title, :year

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully added.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    
    end  

  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:idea])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

    # DELETE /ideas/1
    # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end










end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

    params[:per_page] ||= 25
    params[:page]     ||= 1

    @books = Book.order('created_at DESC').page(params[:page].to_i).per_page(params[:per_page].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/new.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= pluralize(@book.errors.count, "error") + "prohibited this book from being saved:"

      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :author
    %br
    = f.text_field :author
  .field
    = f.label :publisher
    %br
    = f.text_field :publisher
  .field
    = f.label :year
    %br
    = f.text_field :year
  .field
    = f.label :isbn
    %br
    = f.text_field :isbn    

  .actions= f.submit

app/views/books/show.html.haml
%p= @book.title

= link_to "Return Home", pages_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<%# user is logged in, show log out link %>
<% if current_user.present? %>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<%# user is not logged in, show signup and login links %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %> |
  <%= link_to 'Register Now!', new_user_registration_path %>
<% end %>


</body>
</html>

app/views/pages/index.html.haml
%h2 Books

= link_to "Add a book", new_book_path

%ul
  - @books.each do |book|
    %li= link_to book.title, book

= will_paginate @books